application: rohitmoviedatabase
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.app
